### ISSUE TITLE
Move to real arches in Travis

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/packed_simd#300]
QEMU sometimes throws apparently spurious errors, and in any case adds a slowdown. It would be nice to take advantage of the fact that Travis offers the following arch tags:

```yaml
arch: arm64
arch: ppc64le
arch: s390x
```

and actually run on those architectures for the relevant tests.
